version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: task_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: miqvet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: miqvet
    networks:
      - app-network

  frontend:
    build: ../course-work-front
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - PORT=3000
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 